name: Build LaTeX CV
on:
  push:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Check for changes
        id: git-check
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add resume.pdf
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Push PDF
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git commit -m "Automated CV PDF Update"
          git push